import "./editor-codec-browser.js";

export const RICH_TEXT_POLICY = globalThis.DustWaveAdminShellEditorCodec.RICH_TEXT_POLICY;
export const TIMED_TEXT_POLICY = globalThis.DustWaveAdminShellEditorCodec.TIMED_TEXT_POLICY;
export const escapeEditorHtml = globalThis.DustWaveAdminShellEditorCodec.escapeEditorHtml;
export const escapeEditorAttribute = globalThis.DustWaveAdminShellEditorCodec.escapeEditorAttribute;
export const isSafeEditorHref = globalThis.DustWaveAdminShellEditorCodec.isSafeEditorHref;
export const renderEditorInlineMarkdown = globalThis.DustWaveAdminShellEditorCodec.renderEditorInlineMarkdown;
export const markdownToEditorHtml = globalThis.DustWaveAdminShellEditorCodec.markdownToEditorHtml;
export const normalizePastedPlainText = globalThis.DustWaveAdminShellEditorCodec.normalizePastedPlainText;
export const sanitizeClipboardHtml = globalThis.DustWaveAdminShellEditorCodec.sanitizeClipboardHtml;
export const sanitizeClipboardPayload = globalThis.DustWaveAdminShellEditorCodec.sanitizeClipboardPayload;
export const nodeToMarkdown = globalThis.DustWaveAdminShellEditorCodec.nodeToMarkdown;
export const editorElementToMarkdown = globalThis.DustWaveAdminShellEditorCodec.editorElementToMarkdown;
