import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { assertConsumerPin } from '../src/consumer-pin.js';

test('consumer pins check checkout, gitlink, remote, package and lock independently', t => {
  const root = mkdtempSync(join(tmpdir(), 'platform-pin-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const git = (cwd, ...args) => execFileSync('git', ['-C', cwd, ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git(root, 'init');
  const sub = join(root, 'shared/dust-wave-platform');
  mkdirSync(join(sub, 'packages/example'), { recursive: true });
  git(sub, 'init');
  writeFileSync(join(sub, 'packages/example/package.json'), '{"name":"@dustwave/example","version":"1.2.3"}');
  git(sub, 'add', '.');
  git(sub, '-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.test', '-c', 'commit.gpgSign=false', 'commit', '-m', 'fixture');
  const expectedCommit = git(sub, 'rev-parse', 'HEAD');
  const modules = '[submodule "platform"]\npath = shared/dust-wave-platform\nurl = https://github.com/aindaco1/dust-wave-platform.git\n';
  writeFileSync(join(root, '.gitmodules'), modules);
  git(root, 'add', '.gitmodules', 'shared/dust-wave-platform');
  writeFileSync(join(root, 'package-lock.json'), '{"packages":{"shared/dust-wave-platform/packages/example":{"version":"1.2.3"}}}');
  const options = { root, expectedCommit, packages: { example: '1.2.3' }, lockfiles: [{ path: 'package-lock.json', packages: { 'shared/dust-wave-platform/packages/example': '1.2.3' } }] };
  assert.doesNotThrow(() => assertConsumerPin(options));
  assert.throws(() => assertConsumerPin({ ...options, expectedCommit: 'main' }), /immutable commit/);
  assert.throws(() => assertConsumerPin({ ...options, expectedCommit: '0'.repeat(40) }), /checkout differs/);
  assert.throws(() => assertConsumerPin({ ...options, packages: { example: '^1.2.3' } }), /exact package/);
  assert.throws(() => assertConsumerPin({ ...options, packages: { example: '1.2.4' } }), /package version/);
  assert.throws(() => assertConsumerPin({ ...options, expectedRemote: 'https://example.test/wrong.git' }), /remote/);
  assert.throws(() => assertConsumerPin({ ...options, submodulePath: '../outside' }), /leaves root/);
  writeFileSync(join(root, 'package-lock.json'), '{"packages":{}}');
  assert.throws(() => assertConsumerPin(options), /locked version/);
  git(root, 'update-index', '--cacheinfo', `160000,${'1'.repeat(40)},shared/dust-wave-platform`);
  assert.throws(() => assertConsumerPin(options), /Staged gitlink/);
  rmSync(join(sub, '.git'), { recursive: true });
  assert.throws(() => assertConsumerPin(options), /must be initialized/);
});
