import { renderDigestHtml } from '@dustwave/digest-core';
// Scheduling, item selection and the preview destination belong to the app.
// This recipe has no send adapter, recipient list or live provider access.
export function createScheduledPreview({ loadItems, savePreview }) {
  return { async scheduled() {
    const items = await loadItems();
    const html = renderDigestHtml({ subject: 'Example digest', title: 'Example digest', eyebrow: 'Preview',
      introduction: 'Review before adding delivery.', footer: 'Generated by the local example.',
      sections: [{ title: 'Items', items }] });
    await savePreview(html);
  } };
}
